#!/bin/bash
set -e

SCRIPT_DIR=$(dirname $0)
ARTFACTS_DIR=/tmp/artifacts
VERSION=0.8.0

# If there is a zero-length zeppelin tarball, find the version in the
# name and download from Apache
fullname=$(find $ARTIFACTS_DIR -name zeppelin-[0-9.]*\-bin-netinst.tgz)
/bin/sh -x $SCRIPT_DIR/check_for_download $fullname

yum install -y R
yum clean all

{
	cd $ARTFACTS_DIR
	tar xvf zeppelin-$VERSION-bin-netinst.tgz
	mv zeppelin-$VERSION-bin-netinst /opt
	ln -s /opt/zeppelin-$VERSION-bin-netinst /opt/zeppelin
}

chown 185:0 -R /opt/zeppelin/conf && chmod g+rwX -R /opt/zeppelin/conf
chown 185:0 -R /opt/zeppelin/notebook && chmod g+rwX -R /opt/zeppelin/notebook