#!/bin/bash
# Add s2i scripts and make the image S2I-enabled
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

chown -R 185:root $SCRIPT_DIR
chmod -R g+rwX $SCRIPT_DIR

mkdir -p $STI_SCRIPTS_PATH
cp $ADDED_DIR/* $STI_SCRIPTS_PATH
chmod 755  $STI_SCRIPTS_PATH/*