#!/bin/bash
set -e

yum install -y python-pip && yum clean all
pip install --upgrade pip

#Python interpreter lets use conda to install libs and create envs
curl -k https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o miniconda.sh
chmod +x ./miniconda.sh
./miniconda.sh -b -p /opt/miniconda
chown -R 185:0 /opt/miniconda/{envs,pkgs}
chmod 0755 /opt/miniconda/{envs,pkgs}