#!/bin/bash
# Add Cassandra distribution to handle %cassandra interpreters
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

cp $ADDED_DIR/cassandra.repo /etc/yum.repos.d/

yum install -y cassandra && yum clean all