#!/bin/bash
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=$SCRIPT_DIR/added
ARTIFACTS_DIR=/tmp/artifacts
VERSION=0.8.2

# If there is a zero-length zeppelin tarball, find the version in the
# name and download from Apache
fullname=$(find $ARTIFACTS_DIR -name zeppelin-[0-9.]*\-bin-netinst.tgz)
/bin/sh -x $SCRIPT_DIR/check_for_download $fullname

yum install -y R
yum clean all

{
	cd $ARTIFACTS_DIR
	tar xvf zeppelin-$VERSION-bin-netinst.tgz
	mv zeppelin-$VERSION-bin-netinst /opt
	ln -s /opt/zeppelin-$VERSION-bin-netinst /opt/zeppelin
	cp $ADDED_DIR/common.sh /opt/zeppelin/bin
}

chown -R 185:0 /opt/zeppelin-$VERSION-bin-netinst
chmod 0755 /opt/zeppelin-$VERSION-bin-netinst
chmod -R g+rwX /opt/zeppelin-$VERSION-bin-netinst